version: "3"

services:
  api:
    container_name: api
    hostname: api
    build:
      context: app
  api2:
    container_name: api2
    hostname: api2
    build:
      context: app
  main:
    container_name: main
    hostname: main
    build:
      context: reverse-proxy/main
  admin:
    container_name: admin
    hostname: admin
    build:
      context: reverse-proxy/admin
  nginx:
    image: nginx:latest
    ports:
      - 8080:8080
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
      - admin
      - main
