version: "3"

services:
  app1:
    container_name: app1
    hostname: app1
    build:
      context: app
      dockerfile: ../load-balancing/Dockerfile
  app2:
    container_name: app2
    hostname: app2
    build:
      context: app
      dockerfile: ../load-balancing/Dockerfile
  app3:
    container_name: app3
    hostname: app3
    build:
      context: app
      dockerfile: ../load-balancing/Dockerfile
  nginx:
    image: nginx:latest
    ports:
      - 8080:8080
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2
      - app3
